#page title
page_title                                : Tunes Notifier - Notifications for Spotify # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 555731861                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/app/tunes-notifier/id555731861 # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Tunes Notifier                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : $0.99                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Ever wondered what the song you just started to play in Spotify was? Tunes Notifier will tell you its title, artist and album with a notification any time a song starts playing.

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : 56 North Ltd                                
your_link                                 : https://56north.co                     
your_city                                 : Edinburgh üè¥Û†ÅßÛ†Å¢Û†Å≥Û†Å£Û†Å¥Û†Åø                                
email_address                             : support@56north.co
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : jcoynel
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Notification
    description                           : Anytime a new song starts playing
    fontawesome_icon_name                 : bell
    
  - title                                 : Menu bar
    description                           : Check the current song info right in the menu bar
    fontawesome_icon_name                 : bars

  - title                                 : Automatically start at login
    description                           : Forget about the app, let it do it's magic in the background
    fontawesome_icon_name                 : magic

  - title                                 : Discreet
    description                           : Does not appear in the Dock, can be hidden from the menu bar
    fontawesome_icon_name                 : eye-slash
    
  - title                                 : Multilingual
    description                           : Available in English, Danish, Finnish, French, German, Japanese, Portuguese, Spanish, Turkish
    fontawesome_icon_name                 : language
    
  - title                                 : Requirements
    description                           : Spotify and macOS 10.14 or later
    fontawesome_icon_name                 : info-circle
    


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1DB954"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#f03432"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown